# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jimon.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bjimon.proto\x12\x05jimon\"y\n\tMsgUpdate\x12\x13\n\x0bupdate_type\x18\x01 \x01(\x05\x12\x10\n\x08hostname\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0c\n\x04temp\x18\x04 \x01(\x02\x12\x11\n\tcpu_usage\x18\x05 \x01(\x02\x12\x11\n\tmem_usage\x18\x06 \x01(\x02\"\x17\n\x06MsgAck\x12\r\n\x05\x65rrno\x18\x01 \x01(\x05\x32:\n\x05Jimon\x12\x31\n\x0cUpdateAndAck\x12\x10.jimon.MsgUpdate\x1a\r.jimon.MsgAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jimon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MSGUPDATE']._serialized_start=22
  _globals['_MSGUPDATE']._serialized_end=143
  _globals['_MSGACK']._serialized_start=145
  _globals['_MSGACK']._serialized_end=168
  _globals['_JIMON']._serialized_start=170
  _globals['_JIMON']._serialized_end=228
# @@protoc_insertion_point(module_scope)
